data = [
    {
        "color":"Red",
        "size":"10",
        "brand":"Nike",
        "price":"500.00",
        "in_stock":194,
        "imgUrl":"images/redNike.jpeg"
    },
    {"color":"Red",
        "size":"9",
        "brand":"Nike",
        "price":"500.00",
        "in_stock":40,
        "imgUrl":"images/redNike.jpeg"
    },
    {
        "color":"Beige",
        "size":"9",
        "brand":"Nike",
        "price":"500.00",
        "in_stock":37,
        "imgUrl":"images/beigNike.jpeg"
    },
    {
        "color":"Black",
        "size":"10",
        "brand":"Nike",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/blackNike.jpeg"
    },
    {
        "color":"Black",
        "size":"8",
        "brand":"Nike",
        "price":"500.00",
        "in_stock":40,
        "imgUrl":"images/blackNike.jpeg"
    },
    {
        "color":"Blue",
        "size":"8",
        "brand":"Nike",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/blueNike.jpeg"
    },
    {
        "color":"Green",
        "size":"10",
        "brand":"Nike",
        "price":"500.00",
        "in_stock":40,
        "imgUrl":"images/blueNike.jpeg"
    },
    {
        "color":"Green",
        "size":"7",
        "brand":"Nike",
        "price":"500.00",
        "in_stock":40,
        "imgUrl":"images/greenNike.jpeg"
    },
    {
        "color":"White",
        "size":"7",
        "brand":"Nike",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/whiteNike.jpeg"
    },
    {
        "color":"Yellow",
        "size":"10",
        "brand":"Nike",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/yellowNike.jpeg"
    },
    {
        "color":"Black",
        "size":"10",
        "brand":"Adidas",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/blackAdidas.jpeg"
    },
    {
        "color":"Silver",
        "size":"9",
        "brand":"Adidas",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/silverAdidas.jpeg"
    },
    {
        "color":"White",
        "size":"10",
        "brand":"Puma",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/whitePuma.jpeg"
    },
    {
        "color":"Green",
        "size":"6",
        "brand":"Puma",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/greenPuma.jpeg"
    },
    {
        "color":"Black",
        "size":"10",
        "brand":"Allstar",
        "price":"500.00",
        "in_stock":40,
        "imgUrl":"images/blackAllstar.jpeg"
    },
    {
        "color":"Red",
        "size":"5",
        "brand":"Allstar",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/redAllStar.jpeg"
    },
    {
        "color":"Black",
        "size":"10",
        "brand":"Filla",
        "price":"500.00",
        "in_stock":60,
        "imgUrl":"images/redFilla.jpeg"
    },
    {
        "color":"Brown",
        "size":"10",
        "brand":"Canvas",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/brownCanvas.jpeg"
    },
    {
        "coRedlor":"",
        "size":"10",
        "brand":"Dillards",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/redDillards.jpeg"
    },
    {
        "color":"Blue",
        "size":"10",
        "brand":"Sandals",
        "price":"500.00",
        "in_stock":20,
        "imgUrl":"images/blueSandals.jpeg"
    },
    {"color":"Black",
        "size":"10",
        "brand":"Charlotte",
        "price":"500.00",
        "in_stock":40,
        "imgUrl":"images/blackCharlotte.jpeg"
    }
]


const colors = {Red: 47, Beige: 17, Black: 56, Blue: 16, Green: 21, White: 21, Yellow: 11, Silver: 9, Brown: 3}
const sizes = {5: 5, 6: 7, 7: 26, 8: 30, 9: 46, 10: 90}
const brands = {Adidas: 20, Allstar: 12, Canvas: 3, Charlotte: 0, Dillards: 2, Filla: 4, Nike: 143, Puma: 16, Sandals: 1}